###### 1) Загрузить и предварительно обработать данные:

Загрузить данные и проверить их корректность. Проверить наличие пропущенных значений и определить типы данных.

###### 2) Создать новый признак:

Ввести новый признак "марка автомобиля" (company). Идентифицировать производителей автомобилей, представленных в датасете. Внести необходимые коррективы в названия и проверить изменения.

###### 3) Выбрать предикторы и проанализировать корреляцию:

Оставить только ключевые предикторы. Оценить корреляцию между ценой (price) и другими переменными.

###### 4) Преобразовать категориальные переменные:

Использовать pd.get_dummies() для преобразования категориальных переменных.

###### 5) Построить модели линейной регрессии:

Создать модель с одним предиктором - мощность двигателя (horsepower). Оценить процент изменчивости, объясненной данной моделью (R^2).

###### 6) Сравнить модели:

Построить две модели: одну с использованием всех предикторов и вторую без учета марок машин. Сравнить изменения в (R^2), коэффициентах и их значимости. Принять решение о предпочтительной модели.

###### 7) Преобразовать категориальные переменные в фиктивные переменные (dummy variables).Использовать все доступные предикторы для построения модели.

Построение модели со всеми предикторами, кроме марок машин:

Исключить предикторы, относящиеся к маркам машин, и построить модель.

Оценка показателей всех трех моделей:

Вывести сводку результатов для каждой модели, включая R-squared, коэффициенты и значимость предикторов

1) Загрузить и предварительно обработать данные:

Загрузить данные и проверить их корректность. Проверить наличие пропущенных значений и определить типы данных.

In [9]:
import pandas as pd

df = pd.read_csv('cars.csv')
print(df.dtypes)
print(df.describe())
print(df.isna().sum())

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object
           car_ID   symboling   wheelbase   carlength    carwidth   carheight  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000
mean   103.000000    0.834146   98.756585  174.049268   65.907805   53.724878
std     59.322565    1.245307    6.021776   12.337289    2.145204    2.443522
min      1.000000   -2.000000   86.600000  141.100000   60.300000   47.800000
25%     52.000000    0.000000   94.500000  166.300000   64.100000   52.000000
50%    103.000000    1.000000   97.000000  173.200000   65.500000   54.100000
75%    154.000000    2.000000  102.400000  183.100000   66.900000   55.500000
max    205.000000    3.000000  120.900000  208.100000   72.300000   59.800000

        curbweight  enginesize   boreratio      stroke  compressionratio  \
count   205.000000  205.000000  205.000000  205.000000        205.000000
mean   2555.565854  126.907317    3.329756    3.255415         10.142537
std     520.680204   41.642693    0.270844    0.313597          3.972040
min    1488.000000   61.000000    2.540000    2.070000          7.000000
25%    2145.000000   97.000000    3.150000    3.110000          8.600000
50%    2414.000000  120.000000    3.310000    3.290000          9.000000
75%    2935.000000  141.000000    3.580000    3.410000          9.400000
max    4066.000000  326.000000    3.940000    4.170000         23.000000

       horsepower      peakrpm     citympg  highwaympg         price
count  205.000000   205.000000  205.000000  205.000000    205.000000
mean   104.117073  5125.121951   25.219512   30.751220  13276.710571
std     39.544167   476.985643    6.542142    6.886443   7988.852332
min     48.000000  4150.000000   13.000000   16.000000   5118.000000
25%     70.000000  4800.000000   19.000000   25.000000   7788.000000
50%     95.000000  5200.000000   24.000000   30.000000  10295.000000
75%    116.000000  5500.000000   30.000000   34.000000  16503.000000
max    288.000000  6600.000000   49.000000   54.000000  45400.000000
car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

2) Использовать столбец CarName для формирования нового признака "марка автомобиля" (company).

Разбить значения ячеек по пробелу и записать в колонку первый элемент (например, 'audi 100 ls' → 'audi').

Подсчитать общее количество уникальных марок автомобилей в датасете.

Удалить столбец CarName с полным названием машины, так как использование полного наименования нецелесообразно.

Также удалить столбец car_ID, поскольку он не требуется для дальнейшего анализа.

In [46]:
import pandas as pd

df = pd.read_csv('cars.csv')

df['company'] = df.CarName.str.split(' ').apply(lambda x: x[0])
df = df.drop(['car_ID', 'CarName'], axis=1)

df.company.nunique()

28

В результате выполнения данного шага мы успешно создали новый признак "марка автомобиля" (company), используя полное название машины из столбца CarName. Общее количество уникальных марок машин в датасете равно 28. Затем мы удалили столбец car_ID и столбец CarName, так как они не будут использоваться в дальнейшем анализе.

3) Исправление ошибок в уникальных значениях

Исправить ошибки в названиях производителей автомобилей

Подсчитать количество уникальных производителей после коррекции.

Проанализировать, сколько уникальных производителей осталось в итоге.

In [51]:
import pandas as pd

df = pd.read_csv('cars.csv')

df['company'] = df.CarName.str.split(' ').apply(lambda x: x[0])
df = df.drop(['car_ID', 'CarName'], axis=1)

df['company'] = df.company.str.lower()
df['company'] = df.company.replace({'maxda': 'mazda', 'porcshce': 'porsche', 'toyouta': 'toyota', 'vokswagen': 'volkswagen', 'vw': 'volkswagen'})
df.company.nunique()

22

В результате коррекции обнаруженных ошибок в названиях производителей автомобилей мы успешно уменьшили количество уникальных производителей с 28 до 22.

4) Оставить только часть предикторов для предсказания цены:

'company', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower', 'price'.

Создать новый датафрейм с выбранными предикторами.

Посчитать корреляцию между ценой ('price') и остальными переменными в новом датафрейме.

In [76]:
import pandas as pd

df = pd.read_csv('cars.csv')

df['company'] = df.CarName.str.split(' ').apply(lambda x: x[0])
df = df.drop(['car_ID', 'CarName'], axis=1)

df['company'] = df.company.str.lower()
df['company'] = df.company.replace({'maxda': 'mazda', 'porcshce': 'porsche', 'toyouta': 'toyota', 'vokswagen': 'volkswagen', 'vw': 'volkswagen'})

df = df[['price', 'company', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower']]

corr_df = df.corr()
corr_df.sort_values(by=['price'], ascending=False).round(2)

,price,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower
price,1.00,0.58,0.68,0.76,0.84,0.87,0.55,0.81
enginesize,0.87,0.57,0.68,0.74,0.85,1.00,0.58,0.81
curbweight,0.84,0.78,0.88,0.87,1.00,0.85,0.65,0.75
horsepower,0.81,0.35,0.55,0.64,0.75,0.81,0.57,1.00
carwidth,0.76,0.80,0.84,1.00,0.87,0.74,0.56,0.64
carlength,0.68,0.87,1.00,0.84,0.88,0.68,0.61,0.55
wheelbase,0.58,1.00,0.87,0.80,0.78,0.57,0.49,0.35
boreratio,0.55,0.49,0.61,0.56,0.65,0.58,1.00,0.57

В целом, корреляционные результаты подтверждают, что технические характеристики автомобилей, такие как мощность двигателя, размер двигателя, вес, ширина, длина, борирование и колесная база, существенно влияют на цену. Это позволяет сделать предположение о том, что более производительные и комфортабельные автомобили обычно имеют более высокую стоимость, что и очевидно.

5) Применение One-Hot Encoding:

Использовать функцию pd.get_dummies() для создания фиктивных переменных на основе изначальных категорий.

Применить One-Hot Encoding только к категориальным переменным (тип object).

Сравнить результаты с изначальными данными.

Применение One-Hot Encoding ко всему датафрейму:

Применить One-Hot Encoding ко всему датафрейму с тем же набором колонок, что и на предыдущем шаге.

In [75]:
import pandas as pd

df = pd.read_csv('cars.csv')

df['company'] = df.CarName.str.split(' ').apply(lambda x: x[0])
df = df.drop(['car_ID', 'CarName'], axis=1)

df['company'] = df.company.str.lower()
df['company'] = df.company.replace({'maxda': 'mazda', 'porcshce': 'porsche', 'toyouta': 'toyota', 'vokswagen': 'volkswagen', 'vw': 'volkswagen'})

df = df[['price', 'company', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower']]

df_dummy = pd.get_dummies(data=df[['company', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower', 'price']], drop_first = True)
df_dummy

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price,company_audi,company_bmw,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
0,88.6,168.8,64.1,2548,130,3.47,111,13495.0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,88.6,168.8,64.1,2548,130,3.47,111,16500.0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,94.5,171.2,65.5,2823,152,2.68,154,16500.0,0,0,...,0,0,1,0,0,0,1,0,0,0
3,99.8,176.6,66.2,2337,109,3.19,102,13950.0,1,0,...,1,0,0,0,0,1,0,0,0,0
4,99.4,176.6,66.4,2824,136,3.19,115,17450.0,1,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,109.1,188.8,68.9,2952,141,3.78,114,16845.0,0,0,...,1,0,0,0,0,1,0,0,0,0
201,109.1,188.8,68.8,3049,141,3.78,160,19045.0,0,0,...,1,0,0,0,0,1,0,0,0,0
202,109.1,188.8,68.9,3012,173,3.58,134,21485.0,0,0,...,0,0,1,0,0,0,1,0,0,0
203,109.1,188.8,68.9,3217,145,3.01,106,22470.0,0,0,...,1,0,0,0,0,0,1,0,0,0
204,109.1,188.8,68.9,3062,141,3.78,114,22625.0,0,0,...,1,0,0,0,0,1,0,0,0,0

Результаты One-Hot Encoding применены к категориальным переменным. Структура данных изменилась, и теперь включает фиктивные переменные.

6) Использовать библиотеку statsmodels для построения линейной регрессии с одним предиктором – horsepower.

Рассчитать процент изменчивости (R^2) для полученной модели и округлить до целого числа.

In [89]:
import pandas as pd
import statsmodels.formula.api as smf 

df = pd.read_csv('cars.csv')

df['company'] = df.CarName.str.split(' ').apply(lambda x: x[0])
df = df.drop(['car_ID', 'CarName'], axis=1)

df['company'] = df.company.str.lower()
df['company'] = df.company.replace({'maxda': 'mazda', 'porcshce': 'porsche', 'toyouta': 'toyota', 'vokswagen': 'volkswagen', 'vw': 'volkswagen'})

df = df[['price', 'company', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower']]

result = smf.ols('price ~ horsepower', data=df).fit()

print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     382.2
Date:                Tue, 19 Sep 2023   Prob (F-statistic):           1.48e-48
Time:                        19:32:14   Log-Likelihood:                -2024.0
No. Observations:                 205   AIC:                             4052.
Df Residuals:                     203   BIC:                             4059.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3721.7615    929.849     -4.003      0.000   -5555.163   -1888.360
horsepower   163.2631      8.351     19.549      0.000     146.796     179.730
==============================================================================
Omnibus:                       47.741   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.702
Skew:                           1.141   Prob(JB):                     1.22e-20
Kurtosis:                       5.352   Cond. No.                         314.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Модель с одним предиктором horsepower объясняет примерно 65% изменчивости в цене автомобилей. Это говорит о том, что мощность двигателя значительно влияет на стоимость автомобиля.

7) Использовать библиотеку statsmodels для построения линейной регрессии с одним предиктором – horsepower.

Построение модели со всеми предикторами:

Преобразовать категориальные переменные в фиктивные переменные (dummy variables).Использовать все доступные предикторы для построения модели.

Построение модели со всеми предикторами, кроме марок машин:

Исключить предикторы, относящиеся к маркам машин, и построить модель.

Оценка показателей всех трех моделей:

Вывести сводку результатов для каждой модели, включая R-squared, коэффициенты и значимость предикторов.

In [129]:
import pandas as pd
import statsmodels.api as sm

df = pd.read_csv('cars.csv')

df['company'] = df.CarName.str.split(' ').apply(lambda x: x[0])
df = df.drop(['car_ID', 'CarName'], axis=1)

df['company'] = df.company.str.lower()
df['company'] = df.company.replace({'maxda': 'mazda', 'porcshce': 'porsche', 'toyouta': 'toyota', 'vokswagen': 'volkswagen', 'vw': 'volkswagen'})
df = df[['price', 'company', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower']]
df_dummy = pd.get_dummies(data=df[['company', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower', 'price']], drop_first = True)


X = df_dummy.drop(columns=['price'])
Y = df_dummy['price']  
X = sm.add_constant(X)  
model = sm.OLS(Y, X)  
results = model.fit()  
print(results.summary())

X = df_dummy.drop(columns=['price', 'company_audi', 'company_bmw', 'company_buick', 'company_chevrolet', 'company_dodge', 'company_honda', 'company_isuzu', 'company_jaguar', 'company_mazda', 'company_mercury', 'company_mitsubishi', 'company_nissan', 'company_peugeot', 'company_plymouth', 'company_porsche', 'company_renault', 'company_saab', 'company_subaru', 'company_toyota', 'company_volkswagen', 'company_volvo'])
Y = df_dummy['price']  
X = sm.add_constant(X)  
model = sm.OLS(Y, X)  
results = model.fit()  
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.959
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     81.09
Date:                Tue, 19 Sep 2023   Prob (F-statistic):           4.86e-89
Time:                        20:08:04   Log-Likelihood:                -1804.2
No. Observations:                 205   AIC:                             3702.
Df Residuals:                     158   BIC:                             3858.
Df Model:                          46
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                 -3.472e+04   1.17e+04     -2.959      0.004   -5.79e+04   -1.15e+04
wheelbase               147.1396     76.234      1.930      0.055      -3.429     297.708
carlength              -113.2012     48.949     -2.313      0.022    -209.881     -16.522
carwidth                809.1860    214.508      3.772      0.000     385.514    1232.858
curbweight                4.1822      1.582      2.643      0.009       1.057       7.307
enginesize               61.4212     23.643      2.598      0.010      14.724     108.119
boreratio             -4319.4728   1759.825     -2.454      0.015   -7795.288    -843.657
horsepower               34.7010     18.000      1.928      0.056      -0.850      70.252
company_audi            437.1040   2125.971      0.206      0.837   -3761.885    4636.093
company_bmw            7993.4998   2105.132      3.797      0.000    3835.671    1.22e+04
company_buick          3431.0969   2472.252      1.388      0.167   -1451.829    8314.023
company_chevrolet     -2107.0167   2054.269     -1.026      0.307   -6164.387    1950.353
company_dodge         -3034.5530   1686.337     -1.799      0.074   -6365.224     296.118
company_honda         -2328.7396   1622.141     -1.436      0.153   -5532.617     875.138
company_isuzu          -926.1643   1819.489     -0.509      0.611   -4519.823    2667.495
company_jaguar         2695.2664   2546.268      1.059      0.291   -2333.847    7724.379
company_mazda         -1291.5657   1652.561     -0.782      0.436   -4555.527    1972.395
company_mercury       -2762.0259   2786.701     -0.991      0.323   -8266.016    2741.965
company_mitsubishi    -3699.6473   1650.046     -2.242      0.026   -6958.640    -440.654
company_nissan        -1488.1217   1563.564     -0.952      0.343   -4576.305    1600.061
company_peugeot       -2671.4595   1795.328     -1.488      0.139   -6217.398     874.479
company_plymouth      -3052.1258   1670.829     -1.827      0.070   -6352.166     247.915
company_porsche        4915.9715   2797.761      1.757      0.081    -609.864    1.04e+04
company_renault       -2865.2197   2073.046     -1.382      0.169   -6959.676    1229.237
company_saab            719.8222   1767.620      0.407      0.684   -2771.390    4211.035
company_subaru        -1.164e+04   3416.221     -3.407      0.001   -1.84e+04   -4892.375
company_toyota        -2608.7871   1539.320     -1.695      0.092   -5649.086     431.512
company_volkswagen    -2261.9355   1606.886     -1.408      0.161   -5435.683     911.812
company_volvo            68.2605   1943.170      0.035      0.972   -3769.679    3906.200
fueltype_gas           -243.7792    908.310     -0.268      0.789   -2037.774    1550.216
aspiration_turbo        596.6566    676.548      0.882      0.379    -739.588    1932.902
carbody_hardtop       -2556.7157   1213.929     -2.106      0.037   -4954.337    -159.094
carbody_hatchback     -3044.4196   1107.064     -2.750      0.007   -5230.972    -857.867
carbody_sedan         -2256.9173   1154.971     -1.954      0.052   -4538.090      24.256
carbody_wagon         -2815.4970   1223.156     -2.302      0.023   -5231.343    -399.651
drivewheel_fwd         -169.4926    888.585     -0.191      0.849   -1924.531    1585.545
drivewheel_rwd          231.9066   1039.685      0.223      0.824   -1821.566    2285.380
enginetype_dohcv      -8358.0756   4326.239     -1.932      0.055   -1.69e+04     186.645
enginetype_l          -1067.3120   1602.125     -0.666      0.506   -4231.657    2097.033
enginetype_ohc         -273.7175   1063.557     -0.257      0.797   -2374.341    1826.906
enginetype_ohcf        1.031e+04   2672.508      3.857      0.000    5028.873    1.56e+04
enginetype_ohcv       -2393.8587   1214.631     -1.971      0.050   -4792.867       5.150
enginetype_rotor         37.4715   2092.597      0.018      0.986   -4095.600    4170.543
cylindernumber_five   -5235.5232   2887.214     -1.813      0.072   -1.09e+04     466.990
cylindernumber_four   -3741.3604   3542.130     -1.056      0.292   -1.07e+04    3254.673
cylindernumber_six    -5441.5317   2628.646     -2.070      0.040   -1.06e+04    -249.713
cylindernumber_three   1604.1476   2774.698      0.578      0.564   -3876.137    7084.432
cylindernumber_twelve -8097.1585   3616.336     -2.239      0.027   -1.52e+04    -954.561
cylindernumber_two       37.4715   2092.597      0.018      0.986   -4095.600    4170.543
==============================================================================
Omnibus:                       81.075   Durbin-Watson:                   1.382
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              487.187
Skew:                           1.379   Prob(JB):                    1.62e-106
Kurtosis:                      10.031   Cond. No.                     1.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.914
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     72.32
Date:                Tue, 19 Sep 2023   Prob (F-statistic):           9.86e-81
Time:                        20:08:04   Log-Likelihood:                -1881.6
No. Observations:                 205   AIC:                             3817.
Df Residuals:                     178   BIC:                             3907.
Df Model:                          26
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                   -1.7e+04    1.3e+04     -1.309      0.192   -4.26e+04    8625.219
wheelbase                71.1868     87.028      0.818      0.414    -100.552     242.925
carlength               -51.3497     50.341     -1.020      0.309    -150.692      47.993
carwidth                541.8700    253.327      2.139      0.034      41.958    1041.782
curbweight                2.9577      1.796      1.647      0.101      -0.585       6.501
enginesize               36.0515     22.376      1.611      0.109      -8.105      80.208
boreratio             -2230.4519   1731.681     -1.288      0.199   -5647.719    1186.815
horsepower               86.8164     16.717      5.193      0.000      53.827     119.806
fueltype_gas          -2423.0935    975.579     -2.484      0.014   -4348.283    -497.904
aspiration_turbo      -1139.2334    787.230     -1.447      0.150   -2692.738     414.271
carbody_hardtop       -3728.0949   1519.366     -2.454      0.015   -6726.383    -729.807
carbody_hatchback     -4639.1279   1294.594     -3.583      0.000   -7193.855   -2084.401
carbody_sedan         -3337.7854   1356.075     -2.461      0.015   -6013.838    -661.732
carbody_wagon         -4315.4661   1465.089     -2.946      0.004   -7206.646   -1424.287
drivewheel_fwd          297.2402   1121.766      0.265      0.791   -1916.431    2510.912
drivewheel_rwd         1939.1594   1226.536      1.581      0.116    -481.263    4359.582
enginetype_dohcv      -1.713e+04   4540.120     -3.773      0.000   -2.61e+04   -8171.142
enginetype_l           2176.0521   1332.818      1.633      0.104    -454.106    4806.211
enginetype_ohc         4006.5687    897.437      4.464      0.000    2235.584    5777.553
enginetype_ohcf        5421.2822   1388.078      3.906      0.000    2682.076    8160.488
enginetype_ohcv       -5001.2242   1345.435     -3.717      0.000   -7656.280   -2346.169
enginetype_rotor      -5196.6413   2084.532     -2.493      0.014   -9310.217   -1083.066
cylindernumber_five   -1.389e+04   2891.599     -4.802      0.000   -1.96e+04   -8180.353
cylindernumber_four   -1.618e+04   3243.610     -4.989      0.000   -2.26e+04   -9780.800
cylindernumber_six    -1.175e+04   2287.516     -5.135      0.000   -1.63e+04   -7231.547
cylindernumber_three  -9264.0553   4750.899     -1.950      0.053   -1.86e+04     111.279
cylindernumber_twelve -1.214e+04   3386.507     -3.585      0.000   -1.88e+04   -5458.378
cylindernumber_two    -5196.6413   2084.532     -2.493      0.014   -9310.217   -1083.066
==============================================================================
Omnibus:                       18.493   Durbin-Watson:                   1.249
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               50.728
Skew:                           0.293   Prob(JB):                     9.65e-12
Kurtosis:                       5.365   Cond. No.                     1.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

Модель с одним предиктором (horsepower):

R^2=0.653: Мощность двигателя (horsepower) объясняет примерно 65% изменчивости цены автомобилей.

Модель со всеми предикторами:

R^2=0.959: Модель, включающая все предикторы, в том числе и марки машин, хорошо объясняет более 95% изменчивости цены.

Модель со всеми предикторами, кроме марок машин:

R^2=0.914: Этот вариант модели, исключая марки машин, также обладает высоким R^2, равным примерно 91%.


Таким образом, можно сделать вывод, что технические характеристики автомобилей, особенно мощность двигателя, существенно влияют на цену.